[package]
name = "pdb2fasta-wasm-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
knuckles-parse = { version = "0.2.0", default-features = false }
wasm-bindgen = "0.2.95"
