name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bins-v1

      - name: Install cargo-binsall
        uses: cargo-bins/cargo-binstall@main

      - name: Install just
        run: cargo binstall -y just

      - name: Install wasm-pack
        run: cargo binstall -y wasm-pack

      - name: Build deployment
        run:
          just build zip

      - name: Setup FluentCI
        uses: fluentci-io/setup-fluentci@v5
      - name: Deploy
        run: fluentci run --wasm cloudflare pages_deploy deploy --project-name pdb2fasta-rust-wasm-example
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
